version: 2
workflows: # Define a Workflow running the build job, then the deploy job
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master # Only deploys when the commit is on the Master branch
                # - develop
                # - /rc-.*/
              ignore:
                - gh-pages

jobs:
  build:
    docker:
      - image: hanskerkhof/ubuntu-node-awscli:1.5

    working_directory: ~/repo

    steps:
      - checkout

      ## Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --ignore-engines
      #      - run: yarn build-doc

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      ## Lint
      #- run: yarn lint

      # run tests
      #- run: yarn test

      # run e2e tests
      # - run: yarn e2e

      ## build resume HTML
      #- run: yarn gen-resume-hbs

      ## build resume PDF
      #- run: yarn gen-resume-pdf

      ## build
      #- run: yarn build --prod
      ### Prerender does not work! Not enough memory available in the circleci container!
      - run: yarn prerender

      # It's quicker to build the app again in the deploy step
      # - store_artifacts:
      #     path: ~/repo/dist/hans-kerkhof

  deploy:
    docker:
      - image: hanskerkhof/ubuntu-node-awscli:1.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      #- run: yarn test
      #- run: yarn codecov

      #- run: yarn build --prod
      - run: yarn deploy-aws-s3

      - add_ssh_keys:
          fingerprints:
            - "75:53:e9:6c:10:ee:72:9e:51:e7:50:66:7c:cf:f6:e8"

      #- run: yarn deploy-gh-pages
